# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-18 05:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_liked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insta.Image')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insta.Profile')),
            ],
        ),
    ]
