# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-18 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0002_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='user_liked',
            field=models.BooleanField(default=False),
        ),
    ]
